title = 'Xyra'
baseURL = 'https://example.org/'
languageCode = 'en-US'
disableKinds = ['taxonomy']
enableRobotsTXT = true

[params]
  description = "Xudong's personal blog"

[menus]

  [[menus.main]]
    name = 'posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'about'
    pageRef = '/about'
    weight = 25

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

 [markup]
   [markup.highlight]
     lineNos = true
     lineNumbersInTable = true
